server:
  port: 8762

spring:
  application:
    name: service-provider

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    #开启健康检查
    healthcheck:
        enable: true



msg: Hello